### ISSUE TITLE
Auto cannot handle relative paths.

### ISSUE THREAD

**Issue by dbarsam** [dbarsam/python-vsgen#9]
The auto command fails to generate project with relative paths, like '.', and '..'.

**Comment by ChuangTseu** [comment]
Hi, I've been trying to use your tool and stumbled upon this exact problem. 
The fix seems quite easy: just check that the 'filepath' is not an empty string here (https://github.com/dbarsam/python-vsgen/blob/master/vsgen/ptvs/project.py#L87) and here (https://github.com/dbarsam/python-vsgen/blob/master/vsgen/solution.py#L52) otherwise os.makedirs() will throw an error. Which happens when using a local path where the split will yield nothing for the base filepath, since the os.path.normpath() returns a path of the form "the_file.ext".

**Comment by dbarsam** [comment]
@ChuangTseu:  Thanks for using this package.  It's nice to know other people find this useful.

I'm closing this with a local commit that did not get properly pushed to the server.
